# Generated by Django 4.1.7 on 2023-04-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newsimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsimage',
            old_name='news',
            new_name='cseDepartment',
        ),
    ]
