# Generated by Django 4.1.7 on 2023-04-14 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_news_newsimage_csedepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='csedepartment',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csedepartment',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='cseDepartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.csedepartment'),
        ),
    ]
