# Generated by Django 4.1.7 on 2023-04-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_csedepartment_body_alter_csedepartment_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csedepartment',
            old_name='image',
            new_name='poster',
        ),
    ]
