# Generated by Django 4.1.7 on 2023-04-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_cseteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='cseteacher',
            name='role',
            field=models.CharField(choices=[('F', 'Faculty'), ('T', 'Technical_staff')], default='F', max_length=1),
        ),
    ]
