# Generated by Django 4.1.7 on 2023-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_cseteacher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cseteacher',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
