# Generated by Django 4.1.7 on 2023-04-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_cseteacher_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CseDepartment',
            new_name='CseNews',
        ),
    ]
