# Generated by Django 4.1.7 on 2023-04-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_csedepartment_csenews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cseteacher',
            options={'ordering': ['created']},
        ),
    ]
