# Generated by Django 4.1.7 on 2023-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_cseachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cseachievement',
            name='description',
            field=models.TextField(max_length=800),
        ),
    ]
