# Generated by Django 4.1.7 on 2023-04-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_mechnewsimage_mechdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechnews',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mechnewsimage',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
