# Generated by Django 4.1.7 on 2023-04-19 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_civilnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilNewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('civilDepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civilimages', to='website.civilnews')),
            ],
        ),
    ]
