<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-04-19 06:35
=======
# Generated by Django 4.1.7 on 2023-04-19 06:31
>>>>>>> 0f0ccaefc1499fbe7f449537abd6150a93e06c0b

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_civilnewsimage'),
        ('website', '0026_eeenews'),
    ]

    operations = [
    ]
