<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-04-19 07:13
=======
# Generated by Django 4.1.7 on 2023-04-19 07:14
>>>>>>> 181fe85e113faf188c8c6ab65afefae0405ee1f2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_civilevent'),
        ('website', '0028_eeenewsimage'),
    ]

    operations = [
    ]
