# Generated by Django 4.1.7 on 2023-04-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_civilevent'),
        ('website', '0028_eeenewsimage'),
    ]

    operations = [
    ]
