# Generated by Django 4.1.7 on 2023-04-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_eeeevent'),
        ('website', '0031_civilachievement'),
    ]

    operations = [
    ]
