# Generated by Django 4.1.7 on 2023-04-23 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_mbaachievement_mbaevent_mbanews_mbateacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mbanewsimage',
            old_name='mcaDepartment',
            new_name='mbaDepartment',
        ),
    ]
