# Generated by Django 4.1.7 on 2023-04-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
    ]
