# Generated by Django 4.1.7 on 2023-04-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0003_alter_room_options_remove_room_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
